version: 2

enable-beta-ecosystems: true

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"
