.\Scripts\activate
pyinstaller --paths=python python/eeg2bids.py -F `
--name eeg2bids-service-windows `
--add-data 'python/libs/mne;./mne' `
--add-data 'python/libs/mne_bids;./mne_bids' `
--add-data 'python/libs/bids_validator;./bids_validator' `
--hidden-import=eventlet.hubs.epolls `
--hidden-import=eventlet.hubs.kqueue `
--hidden-import=eventlet.hubs.selects `
--hidden-import=eventlet.tpool `
--hidden-import=eventlet.event `
--hidden-import=eventlet.greenio `
--hidden-import=eventlet.greenthread `
--hidden-import=eventlet.patcher `
--hidden-import=eventlet.timeout `
--hidden-import=eventlet.six `
--hidden-import=dns --hidden-import=dns.dnssec --hidden-import=dns.e164 `
--hidden-import=dns.hash --hidden-import=dns.namedict `
--hidden-import=dns.tsigkeyring --hidden-import=dns.update `
--hidden-import=dns.version  --hidden-import=dns.zone `
--hidden-import=engineio.async_drivers.eventlet `
--clean
