"""Generate synthetic, non-sensitive fixtures for EEG2BIDS.

This produces representative inputs and outputs for local debugging *and* the
committed source fixtures the backend test suite (``tests/``) reads. Everything
is deterministic (fixed RNG seed) and small, with no real clinical data.

The EDF/EEGLAB export backends it uses (edfio, eeglabio) are regular runtime
dependencies, so a plain sync is all that is needed:

    uv sync --frozen
    uv run python tools/make_dev_data.py

Two output trees are written:

``dev-data/`` (gitignored, for local debugging):

    eeg_sample.edf        synthetic scalp-EEG recording (input)
    eeg_metadata.json     representative EEG sidecar parameters
    ieeg_sample.edf       synthetic intracranial-EEG recording (input)
    ieeg_metadata.json    representative iEEG sidecar parameters
    bids_valid/           a known-valid BIDS dataset (built with mne-bids)
    bids_invalid/         a copy of bids_valid with one non-BIDS filename

``tests/fixtures/`` (committed; regenerated by this script — see the README
there for provenance). These are deliberately short so the committed bytes stay
small, while remaining structurally representative:

    eeg_continuous.edf    continuous EDF, scalp EEG
    eeg_embedded.set      EEGLAB SET with data embedded in the .set
    eeg_split.set/.fdt    EEGLAB SET metadata + separate .fdt data file
    eeg_epoched.set       epoched EEGLAB SET (rejected: continuous-only)
    ieeg_continuous.edf   continuous EDF, intracranial EEG
    eeg_metadata.json     representative EEG sidecar parameters
    ieeg_metadata.json    representative iEEG sidecar parameters
"""
import argparse
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path

import mne
import numpy as np
from mne_bids import BIDSPath, write_raw_bids
from scipy.io import loadmat, savemat

REPO_ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = REPO_ROOT / 'templates'

SEED = 42
SFREQ_EEG = 256.0
SFREQ_IEEG = 512.0
DURATION_S = 10.0
LINE_FREQ = 60
# A fixed, obviously-synthetic acquisition date keeps output reproducible.
MEAS_DATE = datetime(2020, 1, 1, 12, 0, 0, tzinfo=timezone.utc)

EEG_CHANNELS = ['Fp1', 'Fp2', 'F3', 'F4', 'C3', 'C4', 'O1', 'O2']
IEEG_CHANNELS = ['LAmy1', 'LAmy2', 'LHip1', 'LHip2', 'RAmy1', 'RAmy2']

# The committed test fixtures use a much shorter duration than the dev-data
# recordings so the committed bytes stay small; structure (channels, types,
# sampling rate, formats) is what the tests assert on, not length.
FIXTURE_DURATION_S = 2.0
FIXTURE_EPOCH_TRIALS = 5


def _synthetic_raw(ch_names, ch_type, sfreq, amplitude_v, duration_s=DURATION_S):
    """Build a deterministic RawArray of sine waves plus a little noise."""
    rng = np.random.default_rng(SEED)
    n_samples = int(sfreq * duration_s)
    times = np.arange(n_samples) / sfreq
    data = np.empty((len(ch_names), n_samples))
    for i in range(len(ch_names)):
        freq = 5.0 + i  # a distinct rhythm per channel
        signal = np.sin(2 * np.pi * freq * times)
        noise = rng.standard_normal(n_samples) * 0.1
        data[i] = (signal + noise) * amplitude_v
    info = mne.create_info(ch_names, sfreq, ch_types=ch_type)
    raw = mne.io.RawArray(data, info, verbose='ERROR')
    raw.set_meas_date(MEAS_DATE)
    raw.info['line_freq'] = LINE_FREQ
    return raw


def _write_metadata(template_name, out_path, overrides):
    """Fill a parameters template with representative values."""
    with open(TEMPLATES / template_name) as fd:
        metadata = json.load(fd)
    metadata.update(overrides)
    with open(out_path, 'w') as fd:
        json.dump(metadata, fd, indent=2)


def _write_valid_bids(edf_path, bids_root):
    """Convert an EDF to a valid BIDS dataset the way the app does."""
    if bids_root.exists():
        shutil.rmtree(bids_root)
    raw = mne.io.read_raw_edf(edf_path, verbose='ERROR')
    raw.info['line_freq'] = LINE_FREQ
    bids_path = BIDSPath(
        subject='01', session='01', task='rest',
        datatype='eeg', root=bids_root,
    )
    write_raw_bids(raw, bids_path, overwrite=True, verbose=False,
                   allow_preload=True, format='EDF')


def _write_invalid_bids(valid_root, invalid_root):
    """Copy a valid dataset, then plant one non-BIDS-named file.

    The app validates each file's path against the BIDS naming spec
    (eeg2bids/BIDS.py), so a single mis-named file makes the dataset report
    a validation failure — a known-invalid fixture for the failure path.
    """
    if invalid_root.exists():
        shutil.rmtree(invalid_root)
    shutil.copytree(valid_root, invalid_root)
    stray = (invalid_root / 'sub-01' / 'ses-01' / 'eeg' /
             'not_a_valid_bids_name.txt')
    stray.write_text('This filename is intentionally not BIDS-compliant.\n')


# A MATLAB v5 .mat file opens with a 128-byte header whose first 116 bytes are a
# free-form text description that scipy/eeglabio fill with a "Created on: <date>"
# timestamp. That timestamp is the only non-reproducible part of the .set files;
# overwriting the description with a fixed string (the trailing 12 bytes -- subsys
# offset, version, endian indicator -- are left untouched) makes committed
# fixtures byte-identical across regenerations.
_MAT_HEADER_TEXT_LEN = 116
_MAT_FIXED_DESCRIPTION = (
    b'MATLAB 5.0 MAT-file, EEG2BIDS synthetic fixture (deterministic)'
).ljust(_MAT_HEADER_TEXT_LEN, b' ')


def _normalize_mat_header(mat_path):
    """Replace the .mat header's timestamped description with a fixed string."""
    with open(mat_path, 'r+b') as fd:
        fd.seek(0)
        fd.write(_MAT_FIXED_DESCRIPTION)


def _write_embedded_set(raw, set_path):
    """Write an EEGLAB .set with the data embedded in the .set file itself.

    eeglabio (via ``mne.export``) writes the samples into the .set MATLAB file,
    with no separate .fdt companion.
    """
    mne.export.export_raw(str(set_path), raw, fmt='eeglab', overwrite=True)


def _write_set_fdt(raw, set_path):
    """Write an EEGLAB SET/FDT pair (metadata .set + separate .fdt data file).

    Built by exporting the embedded form, then moving the sample array out into
    a sibling ``.fdt`` file and replacing the ``data`` field with that file's
    name. MNE reads the .fdt as float32 reshaped ``(nbchan, pnts, trials)`` in
    Fortran order, so the samples are written in that order.
    """
    set_path = Path(set_path)
    _write_embedded_set(raw, set_path)

    mat = {k: v for k, v in loadmat(str(set_path)).items()
           if not k.startswith('__')}
    nbchan = int(np.asarray(mat['nbchan']).ravel()[0])
    pnts = int(np.asarray(mat['pnts']).ravel()[0])
    trials = int(np.asarray(mat['trials']).ravel()[0])

    fdt_name = set_path.stem + '.fdt'
    samples = np.asarray(mat['data'], dtype=np.float32)
    samples.reshape(nbchan, pnts, trials, order='F') \
        .ravel(order='F').astype(np.float32).tofile(str(set_path.parent / fdt_name))

    mat['data'] = fdt_name
    savemat(str(set_path), mat, appendmat=False)


def _write_epoched_set(raw, set_path, n_trials):
    """Write an epoched EEGLAB SET (``trials > 1``).

    EEG2BIDS converts continuous recordings only; this fixture drives the
    continuous-only rejection path. The epochs are non-overlapping slices of the
    continuous data, embedded in the .set as an ``(nbchan, pnts, trials)`` array.
    """
    set_path = Path(set_path)
    _write_embedded_set(raw, set_path)

    mat = {k: v for k, v in loadmat(str(set_path)).items()
           if not k.startswith('__')}
    data = np.asarray(mat['data'], dtype=np.float32)  # (nbchan, total_pnts)
    nbchan, total_pnts = data.shape
    epoch_pnts = total_pnts // n_trials
    epoched = data[:, :epoch_pnts * n_trials].reshape(
        nbchan, epoch_pnts, n_trials, order='F')

    mat['data'] = epoched.astype(np.float32)
    mat['trials'] = n_trials
    mat['pnts'] = epoch_pnts
    mat['xmax'] = (epoch_pnts - 1) / float(np.asarray(mat['srate']).ravel()[0])
    savemat(str(set_path), mat, appendmat=False)


def write_test_fixtures(fixtures_dir):
    """Write the committed source fixtures the backend test suite reads.

    Deterministic and short; overwrites in place so re-running the generator
    reproduces byte-identical fixtures (subject to the export backends' own
    output stability). See ``tests/fixtures/README.md`` for provenance.
    """
    fixtures_dir.mkdir(parents=True, exist_ok=True)

    eeg_raw = _synthetic_raw(EEG_CHANNELS, 'eeg', SFREQ_EEG, 50e-6,
                             duration_s=FIXTURE_DURATION_S)
    ieeg_raw = _synthetic_raw(IEEG_CHANNELS, 'seeg', SFREQ_IEEG, 200e-6,
                              duration_s=FIXTURE_DURATION_S)

    mne.export.export_raw(str(fixtures_dir / 'eeg_continuous.edf'), eeg_raw,
                          fmt='edf', overwrite=True)
    mne.export.export_raw(str(fixtures_dir / 'ieeg_continuous.edf'), ieeg_raw,
                          fmt='edf', overwrite=True)
    _write_embedded_set(eeg_raw, fixtures_dir / 'eeg_embedded.set')
    _write_set_fdt(eeg_raw, fixtures_dir / 'eeg_split.set')
    _write_epoched_set(eeg_raw, fixtures_dir / 'eeg_epoched.set',
                       FIXTURE_EPOCH_TRIALS)

    # Strip the timestamped .mat header so the committed .set bytes are stable.
    for set_name in ('eeg_embedded.set', 'eeg_split.set', 'eeg_epoched.set'):
        _normalize_mat_header(fixtures_dir / set_name)

    _write_metadata('eeg_parameters_TEMPLATE.json',
                    fixtures_dir / 'eeg_metadata.json', {
                        'InstitutionName': 'EEG2BIDS Test Fixture',
                        'Manufacturer': 'Synthetic',
                        'ManufacturersModelName': 'make_dev_data',
                        'TaskDescription': 'Synthetic fixture (not real data).',
                        'EEGPlacementScheme': '10-20',
                        'EEGGround': 'Fpz',
                    })
    _write_metadata('ieeg_parameters_TEMPLATE.json',
                    fixtures_dir / 'ieeg_metadata.json', {
                        'InstitutionName': 'EEG2BIDS Test Fixture',
                        'Manufacturer': 'Synthetic',
                        'ManufacturersModelName': 'make_dev_data',
                        'TaskDescription': 'Synthetic iEEG fixture (not real '
                                           'data).',
                    })


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--out', type=Path, default=REPO_ROOT / 'dev-data',
        help='dev-data output directory (default: ./dev-data)',
    )
    parser.add_argument(
        '--fixtures-out', type=Path, default=REPO_ROOT / 'tests' / 'fixtures',
        help='committed test-fixture directory (default: ./tests/fixtures)',
    )
    args = parser.parse_args()
    out = args.out
    out.mkdir(parents=True, exist_ok=True)

    # Inputs: synthetic EEG and iEEG recordings, exported to EDF.
    eeg_raw = _synthetic_raw(EEG_CHANNELS, 'eeg', SFREQ_EEG, 50e-6)
    eeg_edf = out / 'eeg_sample.edf'
    mne.export.export_raw(eeg_edf, eeg_raw, fmt='edf', overwrite=True)

    ieeg_raw = _synthetic_raw(IEEG_CHANNELS, 'seeg', SFREQ_IEEG, 200e-6)
    ieeg_edf = out / 'ieeg_sample.edf'
    mne.export.export_raw(ieeg_edf, ieeg_raw, fmt='edf', overwrite=True)

    # Representative metadata sidecars.
    _write_metadata('eeg_parameters_TEMPLATE.json', out / 'eeg_metadata.json', {
        'InstitutionName': 'EEG2BIDS Dev Fixture',
        'Manufacturer': 'Synthetic',
        'ManufacturersModelName': 'make_dev_data',
        'TaskDescription': 'Synthetic resting-state fixture (not real data).',
        'EEGPlacementScheme': '10-20',
        'EEGGround': 'Fpz',
    })
    _write_metadata(
        'ieeg_parameters_TEMPLATE.json', out / 'ieeg_metadata.json', {
            'InstitutionName': 'EEG2BIDS Dev Fixture',
            'Manufacturer': 'Synthetic',
            'ManufacturersModelName': 'make_dev_data',
            'TaskDescription': 'Synthetic iEEG fixture (not real data).',
        })

    # Outputs: a known-valid and a known-invalid BIDS dataset.
    bids_valid = out / 'bids_valid'
    bids_invalid = out / 'bids_invalid'
    _write_valid_bids(eeg_edf, bids_valid)
    _write_invalid_bids(bids_valid, bids_invalid)

    # Committed test fixtures.
    write_test_fixtures(args.fixtures_out)

    print('Development fixtures written to', out)
    print()
    print('Expected characteristics:')
    print(f'  eeg_sample.edf   {len(EEG_CHANNELS)} EEG ch, '
          f'{SFREQ_EEG:.0f} Hz, {DURATION_S:.0f}s, ~50 uV, line {LINE_FREQ} Hz')
    print(f'  ieeg_sample.edf  {len(IEEG_CHANNELS)} sEEG ch, '
          f'{SFREQ_IEEG:.0f} Hz, {DURATION_S:.0f}s, ~200 uV, '
          f'line {LINE_FREQ} Hz')
    print('  bids_valid/      sub-01 ses-01 task-rest eeg — all files '
          'BIDS-compliant')
    print('  bids_invalid/    same, plus one non-BIDS-named file that fails '
          'validation')
    print()
    print('Committed test fixtures written to', args.fixtures_out)
    print('  eeg_continuous.edf / ieeg_continuous.edf, eeg_embedded.set, '
          'eeg_split.set(+.fdt), eeg_epoched.set, *_metadata.json')


if __name__ == '__main__':
    main()
